app/urls.py
from django.urls import path
from django.conf.urls import url
from .views import *

app_name = 'app'

urlpatterns = [
            path('', MainListView.as_view(), name='index'),
            path('section/<int:pk>/', section, name='section'),
            path('post/<int:pk>/', post, name='post'),
            path('search/', search, name='search'),
            path('post/<int:pk>/update/', update_post, name='update-post'),
            path('post/<int:pk>/delete/', delete_post, name='delete-post'),
            path('comment/<int:pk>/update/', update_comment, name='update-comment'),
            path('comment/<int:pk>/delete/', delete_comment, name='delete-comment'),
            path('post/comment/<int:pk>/', response, name='comment'),
            path('cancel/', cancel, name='cancel'),

]

redd/urls.py
from django.urls import path, include
from django.contrib import admin
from app.views import signup, login, logout


urlpatterns = [
            path('login/', login, name='login'),
            path('logout/', logout, name='logout'),
            path('signup/', signup, name='signup'),
            path('admin/', admin.site.urls),
            path('', include('app.urls')),

]

app/templates/app/commentcore.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load widget_tweaks %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app/css/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">

    <title>Update | Delete</title>
</head>
<body class="b1">

<div class="container">

    <form class="text-center mx-auto my-auto" style="padding-top: 3rem" method="POST">
        {% csrf_token %}
    <div class="row">
    <div class="form-group col-10">

        <div class="row ml-2 mr-2">
            {% if not comment %}
            {{ form.title.errors|striptags }}
            {% render_field form.title class="form-control" rows="2" placeholder="Title your post here" %}
            {% endif %}
        {{ form.text.errors|striptags }}
        {% render_field form.text class="form-control" rows="5" placeholder="What do you think?" %}
            </div>
        <button class="btn btn-sm btn-success btn-block col-2 ml-auto" type="submit">Update</button>
        <button type="button" class="btn btn-sm btn-danger btn-block col-2 ml-auto" data-toggle="modal" data-target="#exampleModal">
            Delete
        </button>
        <!--
        <a class="btn btn-sm btn-secondary btn-block col-2 ml-auto" href="{% url 'app:cancel' %}">Cancel</a>
        -->
  </div>
    </div>
    </form>
</div>




<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure that you want to delete this post?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <a type="submit" class="btn btn-danger" href="{% url 'app:delete-comment' pk %}">Yes</a>
      </div>
    </div>
  </div>
</div>







    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
            <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="js/bootstrap.bundle.min.js"></script>
    </div>

    <!-- CDN JQUERY -->

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

<!--Physical-->

<script src="{% static 'app/js/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'app/js/js/jquery.js' %}"></script>

</body>
</html>

app/templates/app/core.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load humanize %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!--<link rel="stylesheet" href="{% static 'app/css/css/bootstrap.min.css' %}">-->
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    {% block head %} {% endblock %}
    <title>{% block title %} REDD {% endblock %}</title>

</head>
<body class="b1">

    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand text-success" style="margin-left: 3rem;" href="{% url 'app:index' %}"><h3>REDD</h3></a>
            <!--
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                -->
                <div class="collapse navbar-collapse mr-auto" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active ml-4">
                          <a class="btn btn-outline-success btn-sm ml-2" href="{% url 'app:index' %}">Home <span class="sr-only">(current)</span></a>
                        </li>

                        <li class="nav-item ml-2">
                          <button class="btn btn-success btn-sm">{% block section %}Main Section{% endblock %}</button>
                        </li>
                        <!--
                            <li class="nav-item">
                          <a class="nav-link" href="#">Popular Communities</a>
                        </li>
                        -->
                      </ul>
                  <form class="form-inline mt-2 mt-md-0" action="{% url 'app:search' %}" method="GET">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2" type="text" name="query" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                  </form>
                    {% if not request.user.is_authenticated %}
                  <a class="btn btn-success my-2 my-sm-0 base"  href="{% url 'login' %}" role="button">Login</a>
                  <a class="btn btn-success my-2 my-sm-0 base" href="{% url 'signup' %}" role="button">Sign Up</a>
                    {% else %}
                 <a class="btn btn-success my-2 my-sm-0 base"  href="{% url 'logout' %}" role="button">Logout</a>
                  <!--<a class="btn btn-success my-2 my-sm-0 base" href="#" role="button">Login</a>-->
                    {% endif %}
                </div>
            </nav>
           </header>
    <br>
    <br>
    <br>
    <br>
    {% if messages %}
    {% for message in messages %}
    <div class="container">
        <p class="alert alert-success text-center" style="inline-block">
        {{ message }}
        </p>
    </div>
    {% endfor %}
    {% endif %}

    {% block content %}

    {% endblock %}

    <hr class="padding my-3">

    <footer class="container  pb-0">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>&copy; 2017-2020 REDD, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </footer>


  


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
            <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="{% static 'app/js/js/bootstrap.bundle.min.js' %}"></script>
    </div>

    <!-- CDN JQUERY -->

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

<!--
<script src="{% static 'app/js/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'app/js/js/jquery.js' %}"></script>
-->
</body>
</html>

app/templates/app/editpostpage.html
{% extends 'app/update-deletepage.html' %}

{% load static %}

{% block heading %}
<div class="row form-group col-7">

        {{ form.title.errors }}
        {{ form.title }}
                <input type="text"  class="form-control" placeholder="Title" required>
            </div>

{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}

{% load static %}

{% block content %}

<div class="container-md filt py-0 my-0">
        <div class="row">
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
              <h1 class="h2">main</h1>

              <div class="btn-toolbar mb-2 mb-md-0">

                <div class="btn-group mr-2">
                    <a class="btn btn-sm btn-outline-secondary href=">Popular</a>
                    <a class="btn btn-sm btn-outline-secondary href=">Developing</a>
                    <a class="btn btn-sm btn-outline-secondary href=">Recent</a>
                </div>

              </div>
            </div>
        </main>
        </div>
    </div>

{% include 'app/main-card.html' %}

{% endblock %}

app/templates/app/outpage.html
{% extends 'app/reallogin.html' %}

{% load static %}

{% block content %}
<div class="container ml-4 text-center" style="">
<h6>You're logged out of Redd, Inc. To log back in, visit the link below. </h6>
<a class="btn btn-md btn-success" href="{% url 'login' %}">Log In</a>
    </div>
{% endblock %}

app/templates/app/post.html
{% extends 'app/core.html' %}
{% load widget_tweaks %}
{% load humanize %}
{% load static %}
{% block section %}{{post.section.name}}{% endblock %}
{% block content %}

<div class="container-md padding pt-3">
        <div class="row padding mr-2">

            <div class="card col-12 w1 card-outer">
                <div class="card-header">
                <!--
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-info">Like</button>
                    <button type="button" class="btn btn-sm btn-outline-info">Dislike</button>

                </div>
                -->
                    <div style="float:right;">
                    Posted By: <a class="btn btn-sm btn-success" href="">{{post.user}}</a>
                    </div>
                </div>
                <div class="card-body">
                <h5 class="card-title">{{post.title}}</h5>
                <p class="card-text">{{post.text}}</p>
                </div>
                <div class="card-footer">
                    <div>
                    <!--70 Likes   |   86 replies |--> {{post.created_on|naturaltime}}
                    </div>
                    <div style="float:right;">
                    {% if post.user == request.user %}
                    <a href="{% url 'app:update-post' post.pk %}">
                    <button type="button" class="btn btn-sm btn-secondary">Edit/Delete</button>
                    </a>
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>



<div class="container-md">
    <form class="text-center gore" method="POST">
        {% csrf_token %}
        <div class="row vorm">
             {{ form.text.errors|striptags }}

            {% render_field form.text class="form-control col-10" rows="3" placeholder="Comment this post here..." %}

        </div>
        <div class="row vorm">

            <button class="btn col-2 btn-sm btn-outline-success btn-block" type="submit">Comment</button>
        </div>
    </form>
</div>




{% for comment in comments %}
<div class="container-md">
        <div class="row ml-2">

        <div class="card w1 card-outer">
            <div class="card-header">
                <!--
                <div>
                To: <a class="btn btn-sm btn-secondary" href="">John</a>
                </div>
                -->
                <div style="float:right;">
                Responder: <a class="btn btn-sm btn-success" href="">{{comment.user}}</a>
                </div>
            </div>
            <div class="card-body">
                <p class="card-text">{{comment.text}}</p>
            </div>


            <div class="card-footer";>
                <div class="btn-group">
                    <!--
                    <button type="button" class="btn btn-sm btn-outline-primary b-size">Like</button>
                    <button type="button" class="btn btn-sm btn-outline-primary">Dislike</button>
                    <div class="ml-1" style="display:inline-block;">
                    -->
                    <a type="button" class="btn btn-sm btn-secondary" href="{% url 'app:comment' comment.post.id %}">Reply</a>
                </div>
                        {% if comment.user == request.user %}
                        <a type="button" class="btn btn-sm btn-secondary ml-auto" href="{% url 'app:update-comment' comment.id %}">Edit/Delete</a>
                {% endif %}
                <div style="float:right;">
                    <!--70 Likes   |   86 replies |--> {{comment.created_on|naturaltime}}
                    </div>




            </div>

        </div>
        </div>
    </div>
</div>
{% endfor %}


{% endblock %}

app/templates/app/postpage.html
{% extends 'app/core.html' %}

{% load static %}

{% block content %}


<div class="container-md padding pt-5">
        <div class="row padding pt-5">

        <div class="card col-12 w1 card-outer">
            <div class="card-header">
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-success">Like</button>
                    <button type="button" class="btn btn-sm btn-outline-success">Dislike</button>

                </div>
                Poster: <a class="text-success" href="">John</a>
            </div>
            <div class="card-body">
                <h5 class="card-title">Card Title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up
                    the bulk of the card's content.</p>
            </div>
            <div class="card-footer">
                70 Likes   |   86 replies | 2 days ago
                </div>
        </div>
        </div>
    </div>

<div class="container-md">
<div class="row">
<form class="col-12">
    {% csrf_token %}
        {{ form.text.errors }}
        {{ form.text }}
  <div class="form-group">
    <textarea class="form-control" id="description1" rows="3" placeholder="Comment on this post..."></textarea>
  </div>
  <button type="submit" class="btn btn-info">Submit</button>
</form>
</div>
</div>

<div class="container-md">
        <div class="row">

        <div class="card w1 card-outer">
            <div class="card-header">
                Responder: <a class="text-success" href="">John</a>
                </div>
            <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up
                    the bulk of the card's content.</p>
            </div>


            <div class="card-footer";>
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-success b-size">Like</button>
                    <button type="button" class="btn btn-sm btn-outline-success">Dislike</button>
                    <button type="button" class="btn btn-sm btn-outline-success">Reply</button>

                </div>

        </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/app/reallogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app/css/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/signin.css' %}">

    <title>REDD | Login</title>
</head>
<body >
{% block content %}
    <form class="form-signin"; action="{% url 'login' %}" method="POST">
        {% csrf_token %}
        {% if messages %}
    {% for message in messages %}
    <div class="container">
        <p class="alert alert-success text-center" style="inline-block">
        {{ message }}
        </p>
    </div>
    {% endfor %}
    {% endif %}
<!--  <div class="text-center">
  <img class="mb-4" src="../assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
</div>-->
        <h4 class="h3 mb-3 font-weight-normal text-center"><strong>REDD INC</strong></h4>
  <label for="inputEmail" class="sr-only">Username</label>
  <input type="text" id="inputEmail" name="username" class="form-control" placeholder="Username" required autofocus>
  <label for="inputPassword" class="sr-only">Password</label>
  <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
  </div>
  <button class="btn btn-lg btn-success btn-block" type="submit">Log In</button>
  <div class="row text-center ml-2 pt-4">
        <small class="text-muted"> Don't have an account? <a class="btn btn-success btn-sm ml-2" href="{% url 'signup' %}">Create an account</a>
            </small>
    </div>
</form>

{% endblock %}


  



    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
            <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="{% static 'app/js/js/bootstrap.bundle.min.js' %}"></script>


    <!-- CDN JQUERY -->

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

<!--Physical-->
<script src="{% static 'app/js/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'app/js/js/jquery.js' %}"></script>

</body>
</html>

app/templates/app/replypage.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load widget_tweaks %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app/css/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">

    <title>Document</title>
</head>
<body class="b1">



<div class="container">
    <form class="text-center" method="POST" style="padding-top: 3rem">
        {% csrf_token %}
        <div class="row">
            <div class="form-group col-10">
                {{ form.text.errors|striptags }}
                {% render_field form.text class="form-control" rows="5" placeholder="What do you think?" %}
                <button class="btn btn-sm btn-success btn-block col-2 ml-auto" type="submit">Reply</button>
                <a class="btn btn-sm btn-secondary btn-block col-2 ml-auto" href="{% url 'app:post' comment.post.id %}">Cancel</a>
            </div>
        </div>

    </form>
</div>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
            <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="js/bootstrap.bundle.min.js"></script>
    </div>

    <!-- CDN JQUERY -->

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

<!--Physical-->

<script src="{% static 'app/js/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'app/js/js/jquery.js' %}"></script>

</body>
</html>

app/templates/app/search.html
{% extends 'app/core.html' %}

{% load static %}
{% load humanize %}
{% block content %}


<div class="container-md py-5">
    <div class="row padding pt-5">
        <div class="col-5">
            <h3 class="h3">Result(s) for - {{query}}</h3>
        </div>
 <!--       <div class="col-6 col-md-4 btn-group ml-auto">
                    <a class="btn btn-sm btn-outline-secondary text-center href=">Popular</a>
                    <a class="btn btn-sm btn-outline-secondary href=">Developing</a>
                    <a class="btn btn-sm btn-outline-secondary href=">Recent</a>
        </div>-->

    </div>
        <hr>
</div>


    
    

    <!-- Cards -->

{% for post in posts %}
    <div class="container-md">
        <div class="row">
        <div class="card w1 card-outer">
            <div class="card-header">
                <strong class="d-inline-block mb-2" style="color:{{post.section.colour}};"><a href="{{post.section.get_absolute_url}}">{{post.section.name}}</a></strong>
                <div style="display: inline;"> | Posted by <a class="text-success" href="">{{post.user.username}}</a></div>
                </div>
            <div class="card-body">
                <h5 class="card-title"><a href="{{post.get_absolute_url}}" class="text-decoration-none text-reset">{{post.title}}</a></h5>
                <p>{{post.mini_post}}</p>
            </div>
            <div class="card-footer">
                <!--<div>70 Likes | 85 comments</div>-->
                <div class="text-muted" style="display: inline;">{{post.created_on|naturaltime}}</div>
                {% if post.user == request.user %}
                <a href="{% url 'app:update-post' post.pk %}">
                    <button type="button" class="btn btn-sm btn-secondary" style="float: right;">Edit/Delete</button>
                </a>
                    {% endif %}
                </div>
            
    
        </div>
        </div>
    </div>

{% endfor %}
    
{% endblock %}

app/templates/app/secpage.html
{% extends 'app/core.html' %}

{% load static %}
{% load widget_tweaks %}
{% load humanize %}
{% block section %}{{section.name}}{% endblock %}
{% block content %}



<div class="container-md pt-2">
    <div class="row padding pt-5">
        <div class="col-2">
            <h4 class="h3" style="color:{{section.colour}};">{{section.name}}</h4>
        </div>

        <div class="col-6 col-md-4 btn-group ml-auto">
                    <a class="btn btn-sm btn-outline-secondary text-center href=">Learn</a>
                    <a class="btn btn-sm btn-outline-secondary href=">Share</a>
                    <a class="btn btn-sm btn-outline-secondary href=">Be</a>
        </div>

    </div>
        <hr>
</div>

<div class="container-md">
    <form class="text-center gore" method="POST">
        {% csrf_token %}
        <!--{{ form.title.errors }}
        {{ form.title }}-->

        <div class="row vorm">
            {{ form.title.errors|striptags }}

            {% render_field form.title class="form-control col-10" placeholder="Title your post here..." %}
        </div>
        <!--{{ form.text.errors }}
        {{ form.text }}-->
        <div class="row vorm">
            {{ form.text.errors|striptags }}

            {% render_field form.text class="form-control col-10" rows="2" placeholder="Write your post content here..." %}
        </div>
        <div class="row vorm">
            <button class="btn col-2 btn-sm btn-outline-success btn-block" type="submit">Post</button>
        </div>
    </form>
</div>
    
    

    <!-- Cards -->

{% for post in posts %}
    <div class="container-md">
        <div class="row ml-sm-3">
            <div class="card w1 card-outer ml-sm-5">
                <div class="card-header">
                    <strong class="d-inline-block mb-2" style="color:{{post.section.colour}};">{{post.section.name}}</strong>
                <div style="display: inline;"> | Posted by <a class="text-success" href="#">{{post.user.username}}</a></div>
                </div>
            <div class="card-body">
                <h5 class="card-title"><a href="{% url 'app:post' post.id %}" class="text-decoration-none text-reset">{{post.title}}</a></h5>
                <p>{{post.mini_post}}</p>
            </div>
            <div class="card-footer">
                <!--<div>70 Likes | 85 comments</div>-->
                <div class="text-muted" style="display: inline;">{{post.created_on|naturaltime}}</div>
                {% if post.user == request.user %}
                <a href="{% url 'app:update-post' post.pk %}">
                <button type="button" class="btn btn-sm btn-secondary" style="float: right;">Edit/Delete</button>
                </a>
                    {% endif %}
                </div>


        </div>
        </div>
    </div>

{% endfor %}


    {% endblock %}